config/routes.rb
Rails.application.routes.draw do
  get 'timeslots/new'
  get 'timeslots/create'
  devise_for :users
  root to: "pages#home"

  resources :studios do
    resources :rooms, only: %i[new create show]
    resources :reviews, only: %i[new create show]
  end

  resources :rooms, except: %i[new create show destroy] do
    resources :reservations, only: %i[new create show]
  end

  resources :pages, only: %i[show index update edit]
  # Show will be booking page

  resources :reservations, only: %i[edit update index destroy]
  resources :rooms, only: [:destroy]
  resources :timeslot_reservations, only: [:destroy]
  # get "", to: "#"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/pages/_blankequipment.html.erb
<div class="">
              <select class="form-select" name="equipment" aria-label="Default select example" multiple>
                  <option value="" selected>-Equipment-</option>
                  <% %w[piano keyboard drums percussion guitar bass vocals amplifiers accessories audio].each do |equipment| %>
                  <option value="<%=equipment%>"><%= equipment %></option>
                <% end %>
              </select>
          </div>

app/views/pages/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-lewagon nav-bar" data-bs-toggle="modal" data-bs-target="#loginModal">
<a href="/"><img src="/assets/studiobookcropped.png" alt="studiobook" class="nav-logo"></a>
    <ul class="nav-links mb-0">
      <li><a href="#" class="active">Book Studio</a></li>
      <li><%=link_to 'Top studios', studios_path%></li>
      <%# <li><a href="">Support</a></li> %>
    </ul>

    <button class="navbar-toggler text-white" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent" data-bs-toggle="modal" data-bs-target="#loginModal">
      <ul class="navbar-nav me-auto">
          <li class="nav-item mr-5">
            <%= link_to "List your studio here", new_studio_path , class: "nav-link list-studio-btn text-white mr-8" %>
             <%# <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#loginModal">
              Login here
            </button>

            (Not working with collapse)

            <!-- Modal -->
            <div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title">Enter your Login details!</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    <%= render '' %>
                  <%# <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Login</button>
                  </div>
                </div>
              </div>
            </div> %>
          </li>

        <% if user_signed_in? %>
          <li class="nav-item dropdown">
              <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-end text-center" aria-labelledby="navbarDropdown">
                <%= link_to "Account Settings", edit_user_registration_path, class: "dropdown-item" %>
                <%= link_to "Bookings", reservations_path, class: "dropdown-item" %>
                <div class="dropdown-divider"></div>
                <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
              </div>
          </li>
        <% else %>
        <li class="nav-item dropdown align-middle">
              <button class="dropdown-toggler" type="button" id="navbarDropdown" data-bs-toggle="dropdown" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
            <div class="dropdown-menu dropdown-menu-end text-center" aria-labelledby="navbarDropdown">
              <%= link_to "Log in", new_user_session_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to "Sign up", new_user_registration_path, class: "dropdown-item" %>
            </div>
        </li>
        <% end %>
      </ul>
    </div>


    <%# dropdown %>

</nav>

app/views/pages/_searchbar.html.erb
<div class="search-bar search-bar-white main-search">
        <form action="<%= studios_path%>" accept-charset="UTF-8" method="get">
         <%# studio input %>
          <div class="form-floating search-input main-input-1">
            <input type="text" name="query" class="form-control" id="floatingInput" placeholder="E.g Dragon studio">
            <label for="floatingInput" >Find a studio</label>
          </div>
          <%# date input %>
          <div class="form-floating main-input-2">
            <input data-controller="flatpickr" data-flatpickr-date-format="Y-m-d"
                  data-flatpickr-min-date="<%=Time.now%>" name="date"
                   class="form-control" id="floatingInput" placeholder="e.g 25/09/2022">
            <label for="floatingInput">Date</label>
          </div>
          <%# time input %>
          <div class="list-choice mx-1 select main-input-3">
              <select class="form-select" name="time" aria-label="Default select example">
                  <option class="list-choice-title" value="" selected>-Start Time-</option>
                  <% @timeslot_array.each do |time, id| %>
                  <option class="list-choice-object" value="<%=id.to_i%>"><%= time %></option>
                <% end %>
              </select>
          </div>
          <%# duration input %>
          <div class="list-choice mx-1 select main-input-4">
              <select class="form-select" name="duration" aria-label="Default select example">
                  <option class="list-choice-title" value="" selected>-Duration-</option>
                  <% @hour_array.each do |duration, id| %>
                  <option class="list-choice-object" value="<%=id%>"><%= duration %></option>
                <% end %>
              </select>
          </div>
          <button type ="submit"><i class="fa-solid fa-magnifying-glass" data-disable-with="Search"></i></button>
        </form>
    </div>

app/views/pages/home.html.erb
 <%# Header here %>
<div class="nav-header">
<%= render "navbar" %>
    <div class="header-container font-header">
      <h1 class="font-header">Music studio booking made easy</h1>
      <%# Search bar here %>
      <%= render "searchbar" %>
  </div>
</div>
  <%# Discover here %>
<div class="container">
  <h2 class="sub-title">Discover here</h2>
  <div class="discover">
    <% if @studio  %>
    <% @studio.sample(3).each do |studio|  %>
    <div>
      <img src=<%=asset_path('placeholder.jpg')%> alt="">
        <span>
          <%= link_to studio_path(studio), class:"text-decoration-none text-white stretched-link" do %>
          <h3><%= studio.name %></h3>
          <p>From $<%=studio.rooms.sample.price if @studio.first.rooms%></p>
          <% end %>
        </span>
    </div>
    <% end %>
    <% else %>
    <div>
      <img src=<%=asset_path('placeholder.jpg')%> alt="">
        <span>No studios yet</span>
    </div>
    <% end %>

  </div>

  <%# trending rooms, to room index %>
  <h2 class="sub-title">Trending studio rooms</h2>
  <div class="trending">
  <% @studio.reject {|e| e.rooms == []}.sample(4).each do |studio| %>
    <div>
      <img src=<%=asset_path('trending-1.jpg')%> alt="">
      <h3>
       <%= studio.rooms.sample.room_name  %>
      </h3>
    </div>
    <% end %>

  </div>
  <%# call to action %>
  <div class="cta">
    <h3>Sharing<br> is earning now</h3>
    <p>Great oppurtunity to make money by<br>sharing your practice room/studio</p>
    <%= link_to "Start listing", new_studio_path, class: "cta-btn" %>
  </div>
  <h2 class="sub-title">Jammers Stories</h2>
  <div class="stories">
    <div>
        <img src=<%=asset_path('stories-1.jpg')%> alt="">
        <p>The best studio booking experience using StudioBook!</p>
    </div>
    <div>
        <img src=<%=asset_path('stories-2.jpg')%> alt="">
        <p>The best studio booking experience using StudioBook!</p>
    </div>
    <div>
        <img src=<%=asset_path('stories-1.jpg')%> alt="">
        <p>The best studio booking experience using StudioBook!</p>
    </div>
  </div>
  <%= link_to "Start making money", new_studio_path, class: "start-btn" %>
  <%# about message %>
  <div class="about-msg">
    <h2>About StudioBook</h2>
    <p>StudioBook was created by musician that had struggled through the process
    of booking a studio. This platform opens up to more oppurtunity for studio owners, home studio owners,
    as well as fellow musicians and artists that are looking to practice or rehearse with their band.
    </p>
  </div>
  <%# footer design %>
  <div class="footer">
    <a href="#"><i class="fab fa-facebook-f"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-youtube"></i></a>
    <hr>
    <p>Copyright © 2022, StudioBook live</p>
  </div>
</div>