config/routes.rb
Rails.application.routes.draw do
  get 'timeslots/new'
  get 'timeslots/create'
  devise_for :users
  root to: "pages#home"

  resources :studios do
    resources :rooms, only: %i[new create show]
    resources :reviews, only: %i[new create show]
  end

  resources :rooms, except: %i[new create show destroy] do
    resources :reservations, only: %i[new create show]
  end

  resources :pages, only: %i[show index update edit]
  # Show will be booking page

  resources :reservations, only: %i[edit update index destroy]
  resources :rooms, only: [:destroy]
  resources :timeslot_reservations, only: [:destroy]
  # get "", to: "#"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  # create_table "reservations", force: :cascade do |t|
  #   t.string "start_time"
  #   t.integer "price_per_hour"
  #   t.integer "duration"
  #   t.boolean "status"
  #   t.bigint "user_id", null: false
  #   t.datetime "created_at", null: false
  #   t.datetime "updated_at", null: false
  #   t.bigint "timeslot_id"
  #   t.bigint "room_id", null: false
  #   t.date "start_date"
  #   t.string "end_time"
  #   t.date "end_date"

  validates :start_time, :duration, presence: true

  # can be called using reservation.statuses
  # once a reservation has been made, it will show pending, confirmed, and if cancelled, cancelled
  # enum :status, %i[pending confirmed cancelled]
  belongs_to :user
  belongs_to :room
  has_many :timeslot_reservations
  has_many :timeslots, through: :timeslot_reservation
  # has_many :reviews, dependent: :destroy
end

# validates :duration, numericality: { only_integer: true }

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_room, only: %i[create new show]
  # before_action :set_timeslot, only: %i[new create]

  def index
    @reservations = current_user.reservations
    @timeslot_array = timeslot_array
    @hourly_array = hourly_array
    @studio = policy_scope(Studio).find_by(user_id: current_user.id)
    @rooms = policy_scope(Room).where(studio_id: @studio)
    # find all the reservations made for your studio rooms
    @stud_room_id = reservation_lists(@rooms.ids)
    @studio_reservations = policy_scope(Reservation).where(room_id: @stud_room_id)
  end

  def show
    @reservation = Reservation.find(params[:id])
    authorize(@room)
    authorize(@reservation)
    @studio = Studio.find_by(user_id: current_user.id)
    @rooms = Room.where(studio_id: @studio)
    # find all the reservations made for your studio rooms
    @stud_room_id = reservation_lists(@rooms.ids)
    @studio_reservations = Reservation.where(room_id: @stud_room_id)
  end


  def new
    @duration = params[:duration].to_i
    @date = params[:date]
    @reservation = Reservation.new
    authorize(@reservation)
    params[:time] = Timeslot.find(params[:time].to_f).time unless params[:time].blank?
    @timeslot = Timeslot.all
    @hour_array = hourly_array
    # @reservation.total_price = @room.price_per_hour * @reservation.duration
    @timeslot_array = []
    @timeslot.each do |time|
      @timeslot_array << [time.time, time.id]
    end
  end

  def create
    @timeslot = Timeslot.all
    @reservation = Reservation.new(reservation_params)
    authorize(@reservation)
    # assign timeslot_id by taking the value from @reservation.start_time, which signifies timeslot_id
    # @reservation.timeslot_id = params[:reservation][:start_time].to_i
    # find actual start_time by going through the list of timeslot_id and time
    @reservation.timeslot_id = Timeslot.find_by(time: @reservation.start_time).id
    # @start_time = Timeslot.find(params[:start_time]).time
    # reassign the start_time so it's in string
    # @reservation.start_time = @start_time
    # covert start time and date into datetime
    @start_datetime = DateTime.parse "#{@reservation.start_date}T#{@reservation.start_time}+08:00"
    # adding time to calculate @reservation.end_date
    @end_datetime = @start_datetime + (@reservation.duration / 24r)
    @reservation.end_date = @end_datetime
    @reservation.end_time = @end_datetime.strftime("%H:%M")
    # add the rest of the timeslots based on my duration
    @date_timeslots_hash = timeslots_by_day(@start_datetime, @end_datetime)
    # getting [[date_1,timeslot_id1], [date_2,timeslot_id2], etc]
    @date_to_timeslot_id = find_timeslot_id(@date_timeslots_hash)
    @reservation.room = @room
    @reservation.user = current_user
    if @reservation.save
      new_timeslot_reservations(@date_to_timeslot_id, @reservation)
      redirect_to room_reservation_path(@room, @reservation)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    authorize(@reservation)
    @timeslot_reservation = TimeslotReservation.where(reservation_id: params[:id])
    @timeslot_reservation.destroy_all
    @reservation.update_attribute(:status, false)
    redirect_to reservations_path(@reservation), status: :see_other
  end

  # def update
  #   @reservation = Reservation.find(params[:id])
  #   if @reservation.update(reservation_id)
  #     redirect_to(@reservation)
  #   else
  #     render :edit, status: :unprocessable_entity
  #   end
  # end


  private

  def reservation_lists(rooms)
    stud_room_id = []
    Reservation.all.select do |reservation|
      rooms.each do |x|
        stud_room_id << reservation.room_id if reservation.room_id == x
      end
    end
    return stud_room_id
  end

  def new_timeslot_reservations(timeslot_array, reservation)
    # loop through timeslot id(in an array), loop through this array and save each timeslot into timeslots reservations
    timeslot_array.each do |date, timeslot_id|
      TimeslotReservation.create(
        room_id: reservation.room_id,
        date:,
        timeslot_id:,
        reservation_id: reservation.id
      )
    end
  end

  def timeslots_by_day(start_datetime, end_datetime)
    (start_datetime.to_i...end_datetime.to_i).step(30.minutes).to_a.each_with_object({}) do |element, memo|
      day = Time.at(element).to_date.strftime('%Y-%m-%d')
      seconds_since_midnight = Time.at(element).seconds_since_midnight.to_i
      memo[day] ||= []
      memo[day] << seconds_since_midnight
    end
  end

  def find_timeslot_id(timeslots_by_day)
    array = []
    timeslots_by_day.each do |date, times|
      # get an array of timeslot_id
      times_in_secs = Timeslot.where(start_time_in_seconds: times).pluck(:id)
      times_in_secs.each do |time|
        array << [date, time]
      end
    end
    return array
  end

  def set_room
    @room = Room.find(params[:room_id])
  end

  def reservation_params
    params.require(:reservation).permit(:start_time, :duration, :start_date)
  end

  def timeslot_array
    timeslot_array = []
    timeslot = Timeslot.all
    timeslot.each do |time|
      timeslot_array << [time.time, time.id]
    end
    return timeslot_array
  end

  def hourly_array
    @hour_array = []
    time = 1
    23.times do
      if time <= 1
        @hour_array << ["#{time} hour", time]
        time += 0.5
      else
        @hour_array << ["#{time} hours", time]
        time += 0.5
      end
    end
    return @hour_array
  end


  # def time_span_search(start_datetime, end_datetime)
  #   start_is = ((start_datetime.min * 60) + (start_datetime.hour * 3600))
  #   end_is = ((end_datetime.min * 60) + (end_datetime.hour * 3600))
  #   if start_is > end_is
  #     Timeslot.where("start_time_in_seconds >= :start_time
  #                   OR start_time_in_seconds < :end_time", { start_time: start_is,
  #                                                            end_time: end_is }).pluck(:id)
  #   else
  #     Timeslot.where("start_time_in_seconds >= :start_time AND
  #                     start_time_in_seconds < :end_time", { start_time: start_is,
  #                                                           end_time: end_is }).pluck(:id)
  #   end
  #   # using start_time to query start time for first day,
  #   # 1st column - date column - query start_time_date, check start_time that >= start_time .or
  #   # = date column = start_time_date + 1
  #   # check if start_time is < end_time
  # end
end

app/views/reservations/_footer.html.erb
<div class="footer">
    <a href="#"><i class="fab fa-facebook-f"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-youtube"></i></a>
    <hr>
    <p>Copyright © 2022, StudioBook live</p>
</div>

app/views/reservations/_navbar.html.erb
<nav class="nav-bar navbar-white">
     <a href="/"><img src="/assets/studiobookcropped.png" alt="studiobook" class="nav-logo"></a>
</nav>

app/views/reservations/_searchbar.html.erb
    <div class="search-bar search-bar-white">
        <form action="<%= studios_path%>" accept-charset="UTF-8" method="get">

         <%# studio input %>
          <div class="form-floating search-input">
            <input type="text" name="query" class="form-control" id="floatingInput" placeholder="Jamming Studio" value="<%=params[:query]%>">
            <label for="floatingInput" >Find a studio</label>
          </div>
          <%# date input %>
          <div class="form-floating">
            <input data-controller="flatpickr" data-flatpickr-date-format="Y-m-d"
                  data-flatpickr-min-date="<%=Time.now%>" name="date"
                   class="form-control" id="floatingInput" placeholder="e.g 25/09/2022" value="<%=params[:date]%>">
            <label for="floatingInput">Date</label>
          </div>
          <%# time input %>
          <div class="mx-2 select px-2">
              <select class="form-select" name="time" aria-label="Default select example">
                  <option value="" <%= "selected" if params[:time] == "" %>>-Start Time-</option>
                  <% @timeslot_array.each do |time, id| %>
                  <option value="<%=id.to_i%>" <%= "selected" if id == params[:time].to_i %>><%= time %></option>
                <% end %>
              </select>
          </div>
          <%# duration input %>
          <div class="mx-2 select px-2">
              <select class="form-select" name="duration" aria-label="Default select example">
              <option value="" <%= "selected" if params[:duration] == "" %>>-Duration-</option>
                  <% @hour_array.each do |duration, id| %>
              <option value="<%=id%>" <%= "selected" if id == params[:duration].to_f %>><%= id > 1 ? "#{id} hours" : "#{id} hour" %></option>
                  <% end %>
              </select>
          </div>
          <%# <div class="">
              <select class="form-select" name="equipment" aria-label="Default select example" multiple>
                  <option value="" selected>-Equipment-</option>
                  <% Equipment.equipment_types.keys.each do |equipment| %>
                  <%# <option value="<%=equipment%>
                  <%# <%= equipment %>
                  <%# </option> %>
                <%# <% end %>
              <%# </select>  %>
          <%# </div> %>
          <button type ="submit"><i class="fa-solid fa-magnifying-glass" data-disable-with="Search"></i></button>
        </form>
    </div>

app/views/reservations/_searchbar_room.html.erb
<form action="" method="get" class="check-form">
        <div class="room-search-bar">
            <input  data-controller="flatpickr" data-flatpickr-date-format="Y-m-d"
                    data-flatpickr-min-date="<%=Time.now%>" name="date"
                    class="form-control date-input-select" id="floatingInput" placeholder=" Date e.g 25/09/2022">
            <%# <label for="floatingInput">Date</label> %>
        </div>
        <%# time input %>
        <div class=" select">
            <select class="form-select" name="time" aria-label="Default select example">
                <option value="" selected>-Start Time-</option>
                <% @timeslot_array.each do |time, id| %>
                <option value="<%=id%>"><%= time %></option>
            <% end %>
            </select>
        </div>
        <%# duration input %>
        <div class="select">
            <select class="form-select" name="duration" aria-label="Default select example">
                <option value="" selected>-Duration-</option>
                <% @hour_array.each do |duration, id| %>
                <option value="<%=id%>"><%= duration %></option>
            <% end %>
            </select>
        </div>
      <button type="submit">Check Availability</button>
    </form>

app/views/reservations/index.html.erb
<%= render "studios/navbar" %>
<div class="container-booking d-flex row justify-content-between">
    <div class="col-3">
        <div class="left-booking col-10">
            <div class="avatar-profile">
                <img class="avatar-largest" alt="avatar-large" src=<%=asset_path('avatar-3.jpg')%> />
            </div>
            <div class="user-details">
            <a href="<%=edit_user_registration_path(current_user)%>" class="text-decoration-none" style="margin-bottom: px; font-size:20px;">Edit personal info<i class="fa-solid fa-chevron-right text-primary ml-1"></i></a>
                  <hr>
              <h3><%=  "#{current_user.last_name} #{current_user.first_name}" %></h3>
              <p><i class="fa-regular fa-envelope text-secondary" style="margin-right: 5px;"></i>Email: <%= current_user.email %></p>
              <p>
                  Studio owned:  <%= @studio ? @studio.name : "None" %>
              </p>
              <%if @studio  %>
                  <%= link_to "Go to studio", studio_path(@studio), class: 'mt-3' %>
              <% else %>
                  <%= link_to "List a studio", new_studio_path, class: 'mt-3' %>
              <% end %>
              <p>No. of bookings made: <%= @reservations.count %></p>
              <p>No. of bookings for your studio: <%= @studio_reservations.count %></p>
            </div>
        </div>
    </div>
    <div class="right-booking col-8">
        <h2 class="">Your bookings</h2>
        <nav class="tab-btn">
        <div class="nav nav-tabs" id="nav-tab" role="tablist">
          <button class="nav-link active" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-home" type="button" role="tab" aria-controls="nav-home" aria-selected="true">Reservations</button>
          <button class="nav-link" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-profile" type="button" role="tab" aria-controls="nav-profile" aria-selected="false"><%=@studio ? @studio.name : "Your studio" %></button>
        </div>
        </nav>
        <div class="tab-content" id="nav-tabContent">
            <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
                <%# rooms that you have reserved %>
                <% if @reservations != [] %>
                <% @reservations.each do |reservation| %>
                <div class="card-booking">
                    <img src =<%=asset_path('room3.jpg')%> />
                    <div class="card-booking-infos">
                      <h5><%= reservation.room.room_name %></h5>
                      <li class="list-group-item">Start: <%= "#{reservation.start_date} (from #{reservation.start_time})" %> </li>
                      <li class="list-group-item">End: <%= "#{reservation.end_date} (until #{reservation.end_time})" %></li>
                      <li class="list-group-item">Duration: <%= reservation.duration %> hours </li>
                      <% if reservation.status %>
                          <h5 class="confirmed text-success">Booking confirmed</h5>
                      <div class="button btn-booking">
                        <%= link_to "View reservation", room_reservation_path(reservation.room, reservation), class: 'btn btn-secondary mt-5' %>
                        <%= link_to "Go to studio", studio_path(reservation.room.studio), class: 'btn btn-secondary mt-5' %>
                        <%= link_to "cancel reservation", reservation_path(reservation), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: 'btn btn-outline-secondary mt-5 cancel-reservation-btn' %>
                      </div>
                      <% else%>
                      <%# <h3 class="pending text-yellow"> Pending</h3> %>
                      <div class="button btn-booking">
                          <h5 class="cancelled">Cancelled</h5>
                      <%= link_to "View reservation", room_reservation_path(reservation.room, reservation), class: 'btn btn-secondary mt-5' %>
                      <%= link_to "Go to studio", studio_path(reservation.room.studio), class: 'btn btn-secondary mt-5' %>
                      </div>
                      <% end %>
                    </div>
                </div>
                <% end %>
                <% else %>
                <p class="mt-3">No reservations found</p>
                <% end %>
                <%# ^^ rooms that you have reserved %>
            </div>
            <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
            <%# your rooms reservations %>
                <% if @studio_reservations != [] %>
                <% @studio_reservations.each do |reservation| %>
                <div class="card-booking">
                    <img src =<%=asset_path('room3.jpg')%> />
                    <div class="card-booking-infos">
                      <h5><%= reservation.room.room_name %></h5>
                      <li class="list-group-item">Booked by: <%= "#{reservation.user.first_name} #{reservation.user.first_name}" %> </li>
                      <li class="list-group-item">Start: <%= "#{reservation.start_date} (from #{reservation.start_time})" %> </li>
                      <li class="list-group-item">End: <%= "#{reservation.end_date} (until #{reservation.end_time})" %></li>
                      <li class="list-group-item">Duration: <%= reservation.duration %> hours </li>
                      <% if reservation.status %>
                          <h5 class="confirmed text-success">Booking confirmed</h5>
                      <div class="button btn-booking">
                        <%= link_to "View reservation", room_reservation_path(reservation.room, reservation), class: 'btn btn-secondary mt-3' %>
                        <%= link_to "Go to studio", studio_path(reservation.room.studio), class: 'btn btn-secondary mt-3' %>
                        <%= link_to "cancel reservation", reservation_path(reservation), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: 'btn btn-outline-secondary mt-3 cancel-reservation-btn' %>
                      </div>
                      <% else%>
                      <%# <h3 class="pending text-yellow"> Pending</h3> %>
                      <div class="button btn-booking">
                          <h5 class="cancelled">Cancelled</h5>
                      <%= link_to "View reservation", room_reservation_path(reservation.room, reservation), class: 'btn btn-secondary mt-3' %>
                      </div>
                      <% end %>
                    </div>
                </div>
                <% end %>
                <% else %>
                <p class="mt-3">No bookings found...</p>

                <% end %>
            </div>
        </div>
    </div>
</div>
<%= render 'studios/footer' %>

app/views/reservations/new.html.erb
<%= render "navbar" %>
<div class="container-for-list extra-top">
            <h1><span><%= link_to "", studio_path(id: @room.studio_id, query: params[:query], date: params[:date], time: params[:time], duration: params[:duration]), class: "fa-solid fa-chevron-left back-btn text-decoration-none border rounded p-2 text-dark border-secondary" %></span>Request booking</h1>
            <div class="studio"></div>
          <%= simple_form_for [@room, @reservation] do |f| %>
    <div class="list-container mt-0">
        <div class="resv-left-col">
        <%# Add simple form here %>
            <h2 class="mb-3 mt-0">Review your reservation below</h2>
            <div class="studio-info border p-4 pt-4 border-secondary">
                <%# date input %>
                <h3>Start date</h3>
                <%= f.input :start_date, as: :string, input_html:{value: params[:date]}, name:"date", data_controller:"flatpickr", data_flatpickr_date_format:"Y-m-d", data_flatpickr_min_date:"Time.now", label: false, readonly: true %>
                <%= f.hidden_field :start_date, input_html:{value: params[:date], type: "hidden"}, name:"date", data_controller:"flatpickr", data_flatpickr_date_format:"Y-m-d", label: false, data_flatpickr_min_date:"Time.now" %>
                <h3>Start time</h3>
                <%# time input %>
                <%= f.input :start_time, input_html:{value: params[:time]}, name: "time",label: false, readonly: true %>
                <%# duration input %>
                <h3>Duration (No. of hours)</h3>
                <div class="input-group">
                    <% @duration_string = params[:duration].to_i > 1 ? "hours" : "hour" %>
                    <%= f.input :duration, input_html:{value: params[:duration].to_i},label: false, readonly: true %>
                </div>
            </div>
        </div>
    <div class="resv-right-col">

        <h2 class="mb-3 mt-0"><%= @room.studio.name %> Studio</h2>
        <div class="studio-img card-product pt-0">
            <img src="/assets/room2.jpg" alt="" class="rounded">
            <div class="card-product-infos">
                <h2><%= @room.room_name %></h2>
                <p><%= @room.description %></p>
            </div>
        </div>
        <div class="studio-info border p-4 pt-4 mt-4 border-secondary">
            <h2>Price details</h2>
            <h3>Price</h3>
            <div class="filter"><p>$<%= @room.price%> SGD x <%= @duration %> hours</p><span>$ <%= @room.price * @duration.to_f %> SGD</span></div>
            <h3>Booking fee</h3>
            <div class="filter"><p>$0</p><span>$0</span></div>
            <h3>GST (7%)</h3>
            <div class="filter"><p>$<%= ((@room.price * @duration.to_f)* 0.07).round(2) %> SGD</p><span>$<%= ((@room.price * @duration.to_f)* 0.07).round(2) %> SGD</span></div>
            <hr class="line">
            <h3>Grand Total</h3>
            <div class="filter">
                <p class="mb-0">$<%= @room.price * @duration.to_f %> + $0 + $<%= ((@room.price * @duration.to_f)* 0.07).round(2) %></p>
                <span class="h2">$<%= ((@room.price * @duration.to_f) + (@room.price * @duration.to_f* 0.07)).round(2) %> SGD</span>
            </div>
                <%= f.submit "Reserve Now", class: "reserve-button" %>
            <% end %>
        </div>
    </div>
    </div>
</div>

<%= render "footer" %>

app/views/reservations/show.html.erb
  <%= render 'navbar' %>
  <table border="0" cellpadding="0" cellspacing="0" height="100%" width="100%" bgcolor="#F7F7F7">

    <tr>
      <td>
        <table class="content" align="center" cellpadding="0" cellspacing="0" border="0" bgcolor="#F7F7F7" style="margin-top:30px; width: 600px; max-width: 600px;">
          <tr>
            <td colspan="2" style="background: #fff; border-radius: 8px;">
              <table border="0" cellpadding="0" cellspacing="0" width="100%">
                <tr>
                  <td style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;">
                    <tr class="">
                      <td class="grid__col" style="font-family: 'Helvetica neue', Helvetica, arial, sans-serif; padding: 32px 40px; ">

                        <h2 style="color: #404040; font-weight: 300; margin: 0 0 12px 0; font-size: 20px; line-height: 30px; font-family: 'Helvetica neue', Helvetica, arial, sans-serif; ">

        Hi <%= current_user.last_name %>,

</h2>

                        <p style="color: #666666; font-weight: 400; font-size: 15px; line-height: 21px; font-family: 'Helvetica neue', Helvetica, arial, sans-serif; " class="">
                        Your reservation request for <%= @room.room_name %>, <%= @room.studio.name %> has been confirmed. Please review the details of your booking.
                        </p>
                         <table width="100%" border="2" cellspacing="0" cellpadding="0" style="margin-top: 12px; margin-bottom: 12px; margin: 24px 0; color: #666666; font-weight: 400; font-size: 15px; line-height: 21px; font-family: 'Helvetica neue', Helvetica, arial, sans-serif;">
                          <tr>
                            <td style="padding:20px 20px 0px ; font-weight:700; font-size: 25px; ">
                                <%= "#{current_user.last_name} #{current_user.first_name}" %> <br>
                                <p style="padding-top:10px; font-weight:700; font-size: 12px; ">Booking Confirmation Code: 197564</p>
                            </td>
                        </a></td></tr>
                           <tr> <td style="padding:20px 20px 10px ; font-weight:700; font-size: 18px; "><%= @room.studio.name %> <p style="padding-top:0px; font-weight:700; font-size: 12px; "><%= @room.room_name %></p></td>

                           </tr>
                           <tr><td><table style="width: 100%;!important">
                               <tr>

                             </table></td></tr><tr><td  style="padding:5px 5px 0px 20px; font-weight:700; font-size: 12px; "><%= @room.studio.address %></td></tr><tr><td style="width: 100% !important; max-width: 480px !important; height: auto !important;">
                        </a></td></tr>
                           <tr><td>

                             <table style="width: 100%;!important">

                             <tr><td style="padding:20px 20px 0px 20px ; font-weight:700; font-size: 18px; ">Total Payable</td></tr>
    <td style=" colspan=2; padding:20px 20px 5px 20px ; font-weight:300; font-size: 14px;"><%= @room.studio.name %> </td><td></td>
    <td style="  padding:20px 20px 5px 30px ; font-weight:300; font-size: 14px;">S$<%= @room.price.round(2) %></td>

  </tr>

    <td style=" colspan=2; padding:5px 20px 10px 20px ; font-weight:400; font-size: 14px;">All Applicable Taxes </td><td></td>
    <td style="  padding:5px 20px 10px 30px ; font-weight:400; font-size: 14px;">$<%= (@room.price*0.07).round(2) %></td>
     <tr>    <td style=" colspan=2; padding:5px 20px 10px 20px ; font-weight:700; font-size: 14px; color:#000">Grand Total</td><td></td>
       <td  style=" padding:5px 20px 10px 30px ; font-weight:700; font-size: 14px; color:#000;">S$<%= @room.price + @room.price*0.07.round(2) %></td></tr>  <tr>    <td style=" colspan=2; padding:5px 20px 10px 20px ; font-weight:700; font-size: 14px;">Just present this reservation when you arrive!</td><td></td

                             </table></td>


                           </tr>

                           </tr>
                        </table>





                       <!--   <table width="100%" border="0" cellspacing="0" cellpadding="0" style="margin-top: 12px; margin-bottom: 12px; margin: 24px 0">
                          <tr>
                            <td>
                            <table border="0" cellspacing="0" cellpadding="0" width="100%">
                                <tr>
                                  <td style="-webkit-border-radius: 3px; -moz-border-radius: 3px; border-radius: 3px;">
                                    <a href="#" target="_blank" style="display:inline-block; color: #fff; font-weight: 400; border-left: 15px solid; border-right: 15px solid; border-top: 12px solid; border-bottom: 12px solid; font-size: 17px; text-decoration: none; text-align: center; -webkit-text-size-adjust: none; -webkit-border-radius: 3px; -moz-border-radius: 3px; border-radius: 3px; font-family: 'Helvetica neue', Helvetica, arial, sans-serif; background-color: #7ad108; border-color: #7ad108;"
                                      class="btn"> <span style="padding-left: 5px; padding-right: 5px;">
                                Cancel Booking
                            </span>

                                    </a>
                                  </td>
                                </tr>
                              </table>
                            </td>
                          </tr>
                        </table> -->
                        <p style="padding-left:20px; color: #666666; font-weight: 400; font-size: 17px; line-height: 24px; font-family: 'Helvetica neue', Helvetica, arial, sans-serif; margin-bottom: 6px; margin-top: 24px;" class="">Cheers,</p>
                        <p style="padding-left:20px; padding-bottom:10px; color: #666666; font-weight: 400; font-size: 17px;  font-family: 'Helvetica neue', Helvetica, arial, sans-serif; margin-bottom: 6px; margin-top: 10px;">StudioBook Team</p>
                      </td>
                    </tr>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
        </table>
        <div class="btn-reservation mb-5">
            <%= link_to "View bookings", reservations_path, class:"button-show" %>
        </div>
      </td>
    </tr>
</table>

<%= render 'studios/footer' %>