config/routes.rb
Rails.application.routes.draw do
  get 'timeslots/new'
  get 'timeslots/create'
  devise_for :users
  root to: "pages#home"

  resources :studios do
    resources :rooms, only: %i[new create show]
    resources :reviews, only: %i[new create show]
  end

  resources :rooms, except: %i[new create show destroy] do
    resources :reservations, only: %i[new create show]
  end

  resources :pages, only: %i[show index update edit]
  # Show will be booking page

  resources :reservations, only: %i[edit update index destroy]
  resources :rooms, only: [:destroy]
  resources :timeslot_reservations, only: [:destroy]
  # get "", to: "#"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/studio.rb
# == Schema Information
#
# Table name: studios
#
#  id          :bigint           not null, primary key
#  address     :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  name        :string
#  user_id     :bigint
#  postal      :integer
#  description :string
#
class Studio < ApplicationRecord
  has_many :rooms, dependent: :destroy
  validates :address, length: { in: 10..150 }
  validates :address, :postal, :description, presence: true
  validates :description, length: { in: 10..500 }
  # allows us to call: @studio.user
  # belongs_to :owner, class_name: "user", foreign_key: "user_id"
  belongs_to :user
  # validate_associate :user
end

app/controllers/studios_controller.rb
class StudiosController < ApplicationController
  before_action :set_studio, only: %i[show edit update destroy]

  def index
    # if only search is present
    # covert start time and date into datetime
    if params[:query].present?
      @studios = policy_scope(Studio).where("name ILIKE ?", "%#{params[:query]}%")
    elsif params[:date].present? && params[:time].present? && params[:duration].present?
      start_time = Timeslot.find(params[:time]).time unless params[:time].blank?
      start_datetime = DateTime.parse "#{params[:date]}T#{start_time}+08:00"
      end_datetime = start_datetime + (params[:duration].to_i / 24r)
      date_timeslots_hash = timeslots_by_day(start_datetime, end_datetime)
      # timeslot_id_array has nested array of [[date, time],[date,time]]
      timeslot_id_array = find_timeslot_id(date_timeslots_hash)
      room_ids = Room.where(
        <<-SQL
          rooms.id NOT IN (
            SELECT room_id
            FROM timeslot_reservations
            WHERE timeslot_reservations.date = \'#{params[:date]}\'
            AND timeslot_reservations.timeslot_id IN (#{timeslot_id_array.map(&:last).join(', ')})
          )
        SQL
      ).pluck(:id)
      @studios = policy_scope(Studio).joins(:rooms).where("rooms.id IN (#{room_ids.join(', ')})").distinct
    else
      @studios = policy_scope(Studio).all
    end
    @hour_array = hourly_array
    @timeslot = Timeslot.all
    @timeslot_array = []
    @timeslot.each do |time|
      @timeslot_array << [time.time, time.id]
    end
    @room_count = count_rooms
  end

  def show
    @studio = Studio.find(params[:id])
    authorize(@studio)
    @rooms = @studio.rooms
    if params[:date].present? && params[:time].present? && params[:duration].present?
      start_time = Timeslot.find(params[:time]).time unless params[:time].blank?
      start_datetime = DateTime.parse "#{params[:date]}T#{start_time}+08:00"
      end_datetime = start_datetime + (params[:duration].to_i / 24r)
      date_timeslots_hash = timeslots_by_day(start_datetime, end_datetime)
      # timeslot_id_array has nested array of [[date, time],[date,time]]
      timeslot_id_array = find_timeslot_id(date_timeslots_hash)
      @rooms = @studio.rooms.where(
        <<-SQL
          rooms.id NOT IN (
            SELECT room_id
            FROM timeslot_reservations
            WHERE timeslot_reservations.date = \'#{params[:date]}\'
            AND timeslot_reservations.timeslot_id IN (#{timeslot_id_array.map(&:last).join(', ')})
          )
        SQL
      )
    end
    @timeslot = Timeslot.all

    @hour_array = hourly_array
    # @reservation.total_price = @room.price_per_hour * @reservation.duration
    @timeslot_array = []
    @timeslot.each do |time|
      @timeslot_array << [time.time, time.id]
    end
  end

  def new
    @studio = Studio.new
    authorize(@studio)
  end

  def create
    @studio = Studio.new(studio_params)
    @studio.user = current_user
    authorize(@studio)
    if @studio.save
      redirect_to studio_path(@studio)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize(@studio)
  end

  def update
    authorize(@studio)
  end

  def update
    @studio.update(studio_params)
    redirect_to studio_path(@studio)
  end

  def destroy
    authorize(@studio)
    @studio.destroy
    redirect_to root_path, status: :see_other
  end

  helper_method :low_price
  helper_method :range_pax

  private

  # generate date:timeslots hashes
  def timeslots_by_day(start_datetime, end_datetime)
    (start_datetime.to_i...end_datetime.to_i).step(30.minutes).to_a.each_with_object({}) do |element, memo|
      day = Time.at(element).to_date.strftime('%Y-%m-%d')
      seconds_since_midnight = Time.at(element).seconds_since_midnight.to_i
      memo[day] ||= []
      memo[day] << seconds_since_midnight
    end
  end

  def find_timeslot_id(timeslots_by_day)
    array = []
    timeslots_by_day.each do |date, times|
      # get an array of timeslot_id
      times_in_secs = Timeslot.where(start_time_in_seconds: times).pluck(:id)
      times_in_secs.each do |time|
        array << [date, time]
      end
    end
    return array
  end

  def hourly_array
    @hour_array = []
    time = 1
    23.times do
      if time <= 1
        @hour_array << ["#{time} hour", time]
        time += 0.5
      else
        @hour_array << ["#{time} hours", time]
        time += 0.5
      end
    end
    return @hour_array
  end

  def range_pax(studio)
    pax = []
    studio.rooms.each do |room|
      pax << room.total_occupancy
    end
    pax.sort!
    "#{pax.min} to #{pax.max}"
  end

  def low_price(studio)
    price = []
    studio.rooms.each do |room|
      price << room.price
    end
    price.min
  end

  def count_rooms
    room_count = 0
    @studios.each do |studio|
      room_count += studio.rooms.count
    end
    return room_count
  end

  def set_studio
    @studio = Studio.find(params[:id])
  end

  def studio_params
    params.require(:studio).permit(:name, :address, :postal, :description, :user_id)
  end
end

      # elsif params[:equipment].present? && params[:date] == "" && params[:time] == "" && params[:query] == "" && params[:duration] == ""
      # #   # Find by equipment
      #   @studios = Studio.joins(rooms: :equipments).where("equipment.equipment_type ILIKE ?", "%#{params[:equipment]}%")

      # else
      #   sql_query = <<~SQL
      #     studios.name ILIKE :query
      #     AND reservations.start_date ILIKE :query
      #     AND reservations.duration ILIKE :query
      #     AND rooms.equipment_type ILIKE :query
      #   SQL
      #   @studios = Studio.joins(rooms:[:reservations, :equipments]).where(sql_query, query: "%#{params[:query]}%")
      # end

app/views/studios/_footer.html.erb
<div class="footer">
    <a href="#"><i class="fab fa-facebook-f"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-youtube"></i></a>
    <hr>
    <p>Copyright © 2022, StudioBook live</p>
</div>

app/views/studios/_form.html.erb
<div class="container col-4" >
<%= simple_form_for(studio) do |f| %>
<div class="create-studio container-fluid mt-5"  data-controller="equipment">
      <% if @studio.id.present? %>
      <h1><%= @studio.name %></h1>
      <% else %>
      <h1 class="mt-3 mb-3 text-center newroom-title">Create your studio</h1>
      <% end %>
      <div class="room-name-input input-border">
          <%= f.input :name, input_html:{class:"input-border room-name", id:"floatingInput"}, label:"Studio name", label_html: { for: 'floatingInput' } %>
      </div>
      <div class="">
          <div class="input-group">
              <%= f.input :address, label: 'studio address', input_html:{class:"input-border"} %>
          </div>
      </div>
      <div class="description-input input-border mb-4 col-6">
          <%= f.input :postal, input_html:{class:"input-border"} %>
      </div>
      <div class="description-input input-border mb-4">
          <%= f.input :description, input_html:{class:"input-border"} %>
      </div>
  <div class="form-actions room-submit-button text-center ">
  <% if @studio.id.present? %>
  <%= f.submit "Update Studio", class: "btn btn-primary button-show mt-4" %>
  <% else %>
  <%= f.submit "Create Studio", class: "btn button-show align-item-center mt-4" %>
  <% end %>
  </div>
<% end %>
</div>
</div>













<%# <section class="vh-100 bg-image"
  style="background-image: url('https://unsplash.com/photos/XJK8gdWpxWk');">
  <div class="container-fluid py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-xs-12">
        <div class="card rounded-3">
          <img src="https://img.freepik.com/free-photo/acoustic-guitar-recording-studio-room-musicians-rehearsals_169016-3805.jpg?w=1480&t=st=1663073794~exp=1663074394~hmac=5fd82b6973a30501ce31902d25039477a4a14fb847d39be88e1e2480f36a1497"
            class="w-100" style="border-top-left-radius: .3rem; border-top-right-radius: .3rem;"
            alt="Sample photo">
          <div class="card-body p-4 p-md-5">
            <h3 class="mb-4 pb-2 pb-md-0 mb-md-5 px-md-2">Create your Studio!</h3>

            <form class="px-md-2">

              <div class="form-outline mb-4">
              <%= simple_form_for(studio) do |f| %>
              <%#= f.input :name , label: "Floss studio"%>
              <%# </div> %>
                <%#= f.input :address %>
                <%#= f.input :postal %>

              <%# <div class="mb-4">
              </div>
                <%#= f.input :description %>
              <%# <div class="row mb-4 pb-2 pb-md-0 mb-md-5">
                <div class="col-md-6"> %>

                  <%#= f.submit %>
<%#
                </div>
              </div>

            </form>

          </div>
        </div>
      </div>
    </div>
  </div>
</section> %>
<%# end %>

app/views/studios/_navbar.html.erb
<nav class="nav-bar navbar-white">
     <a href="/"><img src="/assets/studiobookcropped.png" alt="studiobook" class="nav-logo"></a>
  <%= render "searchbar" %>
    <div class="nav-buttons d-flex">
    <% if user_signed_in? %>
    <%= link_to "List your studio here", new_studio_path, class: "nav-list-btn nav-list-btn-white" %>
    <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "nav-sign-out-btn nav-sign-out-btn-white" %>
    <% else %>
    <%= link_to "List your studio here", new_studio_path, class: "nav-list-btn nav-list-btn-white" %>
    <%= link_to "Login", new_user_session_path, class: "nav-login-btn nav-login-btn-white" %>
    <a href="#" class="nav-register-btn nav-register-btn-white">Register Now</a>
    <% end %>
    </div>

</nav>

app/views/studios/_room_modal.html.erb
<div class="modal fade" id="exampleModal-<%=room.id%>" tabindex="-1" aria-labelledby="room-modal-label" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="room-modal-label"><%= room.room_name %></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="container-fuid">
      <div class="modal-body">
          <%# adding carouhell images %>
          <div class="row">
              <div class="image-carousel col-md-7 col-s-12">
                  <div id="room-control-carousell-<%=room.id%>" class="carousel slide" data-bs-ride="carousel">
                      <div class="carousel-inner">
                          <div class="img-fluid carousel-item active">
                              <img class="d-block w-300 h-200" src="/assets/room2.jpg" alt="First slide">
                          </div>
                          <div class="img-fluid carousel-item">
                              <img class="d-block w-300 h-200" src="/assets/room3.jpg" alt="Second slide">
                          </div>
                          <div class="img-fluid carousel-item">
                              <img class="d-block w-300 h-200" src="/assets/room5.jpg" alt="Third slide">
                          </div>
                      </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#room-control-carousell-<%=room.id%>" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#room-control-carousell-<%=room.id%>" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                  </div>
              </div>
              <div class="modal-text col-5">
                  <h3><%= room.room_type %></h3>
                  <div class="icon-text">
                      <i class="fa-solid fa-dollar-sign modal-icon"></i>
                      <h5>Price</h5>
                      <p>$<%= room.price %>/hr</p>
                  </div>
                  <div class="icon-text mt-3">
                      <i class="fa-solid fa-house modal-icon"></i>
                      <h5>Room Size</h5>
                      <p><%= room.room_size %>&#13217</p>
                  </div>
                  <div class="icon-text mt-3">
                      <i class="fa-solid fa-user-group modal-icon"></i>
                      <h5>Occupancy</h5>
                      <p><%= room.total_occupancy %> Pax</p>
                  </div>
                  <div class="mt-3">
                      <div class="icon-text">
                          <i class="fa-solid fa-guitar modal-icon"></i>
                          <h5>Room description</h5>
                      </div>
                      <p class="mt-3 col-11"><%= room.description %></p>
                  </div>
              </div>
          </div>
          <div class="equipment-container col-7 mt-4 justify-center">
              <div class="scrollbar overflow-auto">
              <table class='table'>
                  <thead>
                      <tr>
                        <th><h5>Equipment type</h5></th>
                        <th><h5>Name</h5></th>
                        <th><h5>Brand</h5></th>
                      </tr>
                    </thead>
                <tbody>
                <% room.equipments.each do |equipment| %>
                  <tr>
                    <td><%= equipment.equipment_type %></td>
                    <td><%= equipment.name %></td>
                    <td><%= equipment.brand %></td>
                  </tr>
                <% end %>
                </tbody>
              </table>
              </div>
        </div>
          <%# end of carohell images top %>
      </div>
      </div>
      <div class="modal-footer">

        <%# <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button> %>
        <%# <button type="button" class="btn btn-primary">Save changes</button> %>
      </div>
    </div>
  </div>
</div>

      <%# <div class="carousel slide" data-bs-ride="carousel" id="carouselExampleCaptions">
		<div class="carousel-inner">
			<div class="carousel-item active bg-1">
				<div class="carousel-caption">
					<h5>Best In <span class="text-warning">Tourism</span></h5>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus, culpa.</p><a class="bg-warning text-white" href="#">Learn More</a>
				</div>
			</div>
			<div class="carousel-item bg-2">
				<div class="carousel-caption">
					<h5>Worldwide <span class="text-warning">Recognition</span></h5>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus, culpa.</p><a class="bg-warning text-white" href="#">Learn More</a>
				</div>
			</div>
			<div class="carousel-item bg-3">
				<div class="carousel-caption">
					<h5>Effordable <span class="text-warning">Budget</span></h5>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus, culpa.</p><a class="bg-warning text-white" href="#">Learn More</a>
				</div>
			</div>
		</div><button class="carousel-control-prev" data-bs-slide="prev" data-bs-target="#carouselExampleCaptions" type="button"><span aria-hidden="true" class="carousel-control-prev-icon"></span> <span class="visually-hidden">Previous</span></button> <button class="carousel-control-next" data-bs-slide="next" data-bs-target="#carouselExampleCaptions" type="button"><span aria-hidden="true" class="carousel-control-next-icon"></span> <span class="visually-hidden">Next</span></button> <!--thumbnails-->
		<div class="carousel-indicators">
			<button aria-label="Slide 1" class="active" data-bs-slide-to="0" data-bs-target="#carouselExampleCaptions" type="button"><img class="img-fluid" src="img/1.jpg"></button> <button aria-label="Slide 2" data-bs-slide-to="1" data-bs-target="#carouselExampleCaptions" type="button"><img class="img-fluid" src="img/2.jpg"></button> <button aria-label="Slide 3" data-bs-slide-to="2" data-bs-target="#carouselExampleCaptions" type="button"><img class="img-fluid" src="img/3.jpg"></button>
		</div>
	</div> %>

app/views/studios/_searchbar.html.erb
    <div class="search-bar search-bar-white">
        <form action="<%= studios_path%>" accept-charset="UTF-8" method="get">

         <%# studio input %>
          <div class="form-floating search-input">
            <input type="text" name="query" class="form-control" id="floatingInput" placeholder="Jamming Studio" value="<%=params[:query]%>">
            <label for="floatingInput" >Find a studio</label>
          </div>
          <%# date input %>
          <div class="form-floating">
            <input data-controller="flatpickr" data-flatpickr-date-format="Y-m-d"
                  data-flatpickr-min-date="<%=Time.now%>" name="date"
                   class="form-control" id="floatingInput" placeholder="e.g 25/09/2022" value="<%=params[:date]%>">
            <label for="floatingInput">Date</label>
          </div>
          <%# time input %>
          <div class="mx-2 select px-2">
              <select class="form-select" name="time" aria-label="Default select example">
                  <option value="" <%= "selected" if params[:time] == "" %>>-Start Time-</option>
                  <% @timeslot_array.each do |time, id| %>
                  <option value="<%=id.to_i%>" <%= "selected" if id == params[:time].to_i %>><%= time %></option>
                <% end %>
              </select>
          </div>
          <%# duration input %>
          <div class="mx-2 select px-2">
              <select class="form-select" name="duration" aria-label="Default select example">
              <option value="" <%= "selected" if params[:duration] == "" %>>-Duration-</option>
                  <% @hour_array.each do |duration, id| %>
              <option value="<%=id%>" <%= "selected" if id == params[:duration].to_f %>><%= id > 1 ? "#{id} hours" : "#{id} hour" %></option>
                  <% end %>
              </select>
          </div>
          <%# <div class="">
              <select class="form-select" name="equipment" aria-label="Default select example" multiple>
                  <option value="" selected>-Equipment-</option>
                  <% Equipment.equipment_types.keys.each do |equipment| %>
                  <%# <option value="<%=equipment%>
                  <%# <%= equipment %>
                  <%# </option> %>
                <%# <% end %>
              <%# </select>  %>
          <%# </div> %>
          <button type ="submit"><i class="fa-solid fa-magnifying-glass" data-disable-with="Search"></i></button>
        </form>
    </div>

app/views/studios/_studioshow.html.erb
<section class="bg-light pb-5 shadow-sm">
  <div class="container">
    <div class="row pt-5">
      <div class="col-12">
        <h1 class="text-uppercase border-bottom mb-4"><%= @studio.name %> - for users and host</h1>
        <h5><%= @studio.rooms.count%> rooms for booking </h5>
      </div>
    </div>
    <div class="row">
        <% @studio.rooms.each do |room|%>
      <div class="col-lg-3 mb-3 d-flex align-items-stretch ">
        <div class="card">
            <img src="<%= asset_path('room2.jpg')%>" class="card-img-top"/>
          <div class="card-body d-flex flex-column">
            <h4 class="card-title"><%= room.room_name %></h4>
            <p class="card-text mb-4"><%= room.description %></p>
            <%= link_to "", studio_room_path(@studio, room), class: 'stretched-link' %>
            <%# enum to show string instead of integer value %>
            <li class="list-group-item">Room Type: <%= room.room_type %></li>
            <li class="list-group-item">Size: <%= room.room_size %>&#13217;</li>
            <li class="list-group-item">Price: <%= room.price %></li>
            <li class="list-group-item">Suggested Pax: <%= room.total_occupancy %></li>
          </div>
        </div>
      </div>
        <% end %>
    </div>
    <div class="list-group px-3 col-2">
<%= link_to "Create A Room", new_studio_room_path(@studio), method: :get, class: 'btn btn-primary mb-2' %>
<%# <%= link_to "Delete Studio", studio_path(@studio), method: :delete, form: {data: {turbo_confirm: 'Are you sure?'}}, class: 'btn btn-primary px-4' %>
<%= link_to "Delete Studio", studio_path(@studio), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: 'btn btn-outline-danger px-4' %>
</div>
  </div>

</section>

app/views/studios/edit.html.erb
<div class="studio-background">
    <%= render "pages/navbar" %>
    <%= render "form", studio: @studio %>
</div>
    <%= render 'footer' %>

app/views/studios/new.html.erb
<div class="studio-background">
    <%= render "pages/navbar" %>
    <%= render "form", studio: @studio %>
</div>
    <%= render 'footer' %>

app/views/studios/show.html.erb
<%= render "navbar", studio: @studio %>
<div class="studio-details">
    <div class="studio-title">
        <h1><%=@studio.name%>
        <% if policy(@studio).edit? %>
        <%= link_to "Edit", edit_studio_path(@studio), class:"btn btn-secondary py-2" %>
        <% end %>
        <% if policy(@studio).destroy? %>
        <%= link_to "Delete studio", studio_path(@studio), data: { turbo_method: :delete , turbo_confirm: 'Are you sure?'}, class: 'btn btn-outline-secondary py-2' %>
        <% end %>
        </h1>
        <div class="studio-title-row">
            <div>
                <%# insert reviews start here %>
                <i class="fa-solid fa-star"></i>
                <i class="fa-solid fa-star"></i>
                <i class="fa-solid fa-star"></i>
                <i class="fa-solid fa-star"></i>
                <i class="fa-solid fa-star"></i>
                <%# insert studio.reviews.count here %>
                <span>245 reviews</span>
            </div>
            <div>
                <p>Location: <%= @studio.address %>, <%= @studio.postal %> </p>
            </div>
        </div>
    </div>
    <div class="gallery">
        <div class="gallery-img-1"><img src="/assets/rehearsal-1.jpg"></div>
        <div><img src="/assets/rehearsal-2.jpg"></div>
        <div><img src="/assets/rehearsal-3.jpg"></div>
        <div><img src="/assets/rehearsal-4.jpg"></div>
        <div><img src="/assets/rehearsal-5.jpg"></div>
    </div>
    <div class="small-details">
        <h2><%= @studio.description %></h2>
        <%# li the equipment list in table rows %>
        <%# <p>Equipment available</p> %>
        <%# consider creating room card to link to rooms %>
        <%# <h4>$100/hour</h4> %>
    </div>
    <hr class="line">
    <h2>Select your availability</h2>
    <form action=<%= studio_path(@studio) %> method="get" class="check-form">
        <div class="">
            <input  data-controller="flatpickr" data-flatpickr-date-format="Y-m-d"
                    data-flatpickr-min-date="<%=Time.now%>" name="date"
                    class="form-control date-input-select border text-dark" placeholder=" Date e.g 25/09/2022"
                    value="<%=params[:date]%>" required>
        </div>
        <%# time input %>
        <div class=" select">
            <select class="form-select bg-white border" name="time" aria-label="Default select example">
                <option value="" <%= "selected" if params[:time] == "" %>>-Start Time-</option>
                  <% @timeslot_array.each do |time, id| %>
                <option value="<%=id.to_i%>" <%= "selected" if id == params[:time].to_i %>><%= time %></option>
            <% end %>
            </select>
        </div>
        <%# duration input %>
        <div class="select">
            <select class="form-select bg-white border" name="duration" aria-label="Default select example">
                <option value="" <%= "selected" if params[:duration] == "" %>>-Duration-</option>
                  <% @hour_array.each do |duration, id| %>
                  <% @duration_string = id > 1 ? "#{id} hours" : "#{id} hour"  %>
                <option value="<%=id%>" <%= "selected" if id == params[:duration].to_f %>><%= @duration_string %></option>
            <% end %>
            </select>
        </div>
      <button type="submit">Change search</button>
    </form>
</div>

<div class="container">
    <h1><%= @studio.rooms.count%> Rooms available for you</h1>
    <% @studio.rooms.each do |room| %>
    <%# figure out how to stretched link the entire block %>
    <%# <%= link_to studio_room_path(@studio, room)%>
    <div class="studio">
        <div class="studio-img">
            <%=  render "room_modal", room: room %>
            <button type="button" data-bs-toggle="modal" class="btn btn-link no-decoration" data-bs-target="#exampleModal-<%=room.id%>">
            <img src="<%= [ asset_path('room2.jpg'), asset_path('room3.jpg'), asset_path('room5.jpg')].sample %>" alt="">
            </button>
        </div>
        <div class="studio-info">
            <h3><%= room.room_name %></h3>
            <p><%= room.description %></p>
            <div class="studio-price">
                <p><%= room.total_occupancy%> Pax</p>
                <h4>$<%=room.price %><span>/ hour</span></h4>
                <div class="box-3">
                    <%= link_to "Book Now", new_room_reservation_path( room_id: room, query: params[:query],
                                                                       date: params[:date], time: params[:time],
                                                                       duration: params[:duration]),
                                                                       class: "button-show" %>
                </div>
                <% if policy(@studio).edit? %>
                    <%= link_to "Edit room", edit_room_path(room), class:"btn btn-secondary py-2" %>
                    <%= link_to "Delete room", room_path(room), data: { turbo_method: :delete , turbo_confirm: 'Are you sure?'}, class: 'btn btn-outline-secondary py-2' %>
                <% end %>
            </div>
        </div>
      </div>
    <% end %>
    <%# only for studio owner === current_user %>
    <hr class="line-full">
    <% if policy(@studio).edit?  %>
    <hr class="line">
    <div class="add-room-btn mt-4">
      <div class="button-show plus-button p-12">
          <%= link_to new_studio_room_path(@studio) do %>
          <i class="fa-solid fa-plus plus-button stretched-link"></i>
          <% end %>
      </div>
      <h3>Add room</h3>
    </div>
    <% end %>
    <%# only for studio owner, end above%>
  </div>
    <%# only for studio owner, end above%>
    </div>
</div>
<%= render "footer", studio: @studio %>